### ISSUE TITLE
_reduxModuleBuilder.createApiMiddleware is not a function

### ISSUE THREAD

**Issue by alvarosaavedra** [fullstackreact/react-gen-generator#3]
Using yo react-gen --redux, you need to install extra react-router-redux.

After that the web console show configureStore.js?8e54:12 Uncaught TypeError: (0 , _reduxModuleBuilder.createApiMiddleware) is not a function

**Comment by auser** [comment]
Yikes. Thanks for the update! I'll update this right now.

**Comment by auser** [comment]
Should be fixed with the latest push.

Thanks for notifying @alvarosaavedra!

**Comment by alvarosaavedra** [comment]
@auser   I still get 
configureStore.js?8e54:12 Uncaught TypeError: (0 , _reduxModuleBuilder.createApiMiddleware) is not a function

in the web console
